// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jugxnvkjyzgepkzzqjwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1Z3hudmtqeXpnZXBrenpxandsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODA1NTAsImV4cCI6MjA3MTM1NjU1MH0.Ci1uga23LGBEkVIJftwk3FxFASba9oiCqE5LiPxlfIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});